name: Build Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: python-package
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build cloudsmith-cli

      - name: Build package
        run: python -m build --verbose

      - name: Upload artifact
        run: cloudsmith push python --api-key 95e54aaea50edd3f1841bda4fc3a1b3eaa6c545d workspace-for-rajdeep/ne dist/*.tar.gz
