name: Promote Python Package

on:
  workflow_dispatch:
    inputs:
      event_type:
        description: "Event type for package promotion"
        required: true
        type: string

env:
  CLOUDSMITH_NAMESPACE: workspace-for-rajdeep
  CLOUDSMITH_STAGING_REPO: 'ne'
  CLOUDSMITH_PRODUCTION_REPO: 'staging'
  CLOUDSMITH_SERVICE_SLUG: bot-wSY1
  PACKAGE_NAME: 'proj'

permissions:  
   id-token: write # Required for requesting the JWT 
   contents: read  # Required for actions/checkout

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with Cloudsmith
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          oidc-namespace: 'workspace-for-rajdeep'
          oidc-service-slug: 'bot-wSY1'

      - name: Get All Packages Tagged as Ready-for-Production
        run: |
          # List all packages tagged with ready-for-production
          PACKAGE_DATA=$(cloudsmith list package $CLOUDSMITH_NAMESPACE/$CLOUDSMITH_STAGING_REPO --tag "ready-for-production" -F json)

          IDENTIFIERS=$(echo "$PACKAGE_DATA" | jq -r '.data[].identifier_perm')

          if [ -z "$IDENTIFIERS" ]; then
            echo "No packages found with ready-for-production tag."
            exit 1
          fi

          echo "Found packages for promotion:"
          echo "$IDENTIFIERS"

          # Store identifiers for later use
          echo "IDENTIFIERS=$IDENTIFIERS" >> $GITHUB_ENV
        shell: bash

      - name: Promote Ready-for-Production Packages to Production
        run: |
          for ID in $IDENTIFIERS; do
            echo "Promoting package $ID to production..."
            cloudsmith mv --yes \
              $CLOUDSMITH_NAMESPACE/$CLOUDSMITH_STAGING_REPO/$ID \
              $CLOUDSMITH_PRODUCTION_REPO
          done
        shell: bash
