name: Promote Python Package

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Event type for package promotion"
        required: true
        type: string
      package_version:
        required: true
        type: string

env:
  CLOUDSMITH_NAMESPACE: workspace-for-rajdeep
  CLOUDSMITH_STAGING_REPO: 'ne'
  CLOUDSMITH_PRODUCTION_REPO: 'staging'
  CLOUDSMITH_SERVICE_SLUG: bot-wSY1

permissions:  
   id-token: write # Required for requesting the JWT 
   contents: read  # Required for actions/checkout

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with Cloudsmith
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          oidc-namespace: 'workspace-for-rajdeep'
          oidc-service-slug: 'bot-wSY1'

      - name: Tag Package as Ready-for-Production
        run: |
          PACKAGE_NAME="${{ github.event.inputs.package_name }}"
          PACKAGE_VERSION="${{ github.event.inputs.package_version }}"
          
          echo "Tagging package $PACKAGE_NAME-$PACKAGE_VERSION as ready-for-production..."
          
          PACKAGE_QUERY="filename:${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz"
          PACKAGE_DATA=$(cloudsmith list package $CLOUDSMITH_NAMESPACE/$CLOUDSMITH_STAGING_REPO -q "$PACKAGE_QUERY" -F json)
          
          IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm')

          if [ -z "$IDENTIFIER" ] || [ "$IDENTIFIER" = "null" ]; then
            echo "Error: Failed to find package identifier."
            exit 1
          fi
          
          echo "Found package identifier: $IDENTIFIER"

          # Tag the package
          cloudsmith tag set $CLOUDSMITH_NAMESPACE/$CLOUDSMITH_STAGING_REPO/$IDENTIFIER ready-for-production
          echo "Tagged package $IDENTIFIER as ready-for-production."
          
          echo "IDENTIFIER=$IDENTIFIER" >> $GITHUB_ENV
        shell: bash

      - name: Promote Tagged Package to Production
        run: |
          echo "Promoting package $IDENTIFIER to production..."
          cloudsmith mv --yes \
            $CLOUDSMITH_NAMESPACE/$CLOUDSMITH_STAGING_REPO/$IDENTIFIER \
            $CLOUDSMITH_PRODUCTION_REPO
        shell: bash
