name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
    branches:
      - main

env:
  CLOUDSMITH_NAMESPACE: workspace-for-rajdeep
  CLOUDSMITH_REPOSITORY: "staging"
  CLOUDSMITH_SERVICE_SLUG: bot-wSY1

permissions:
  actions: read
  id-token: write  # Required for requesting the JWT
  contents: read   # Required for actions/checkout

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist
          repository: ${{ github.repository }}
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}



      - name: List directory contents
        run: ls -la dist/
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build cloudsmith-cli

      - name: Authenticate with Cloudsmith
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          oidc-namespace: ${{ workspace-for-rajdeep }}
          oidc-service-slug: ${{  bot-wSY1 }}
          
      - name: Push package to Cloudsmith
        run: |
          if ! ls dist/*.tar.gz 1> /dev/null 2>&1; then
            echo "No package found to upload"
            exit 1
          fi
           cloudsmith push python --api-key 95e54aaea50edd3f1841bda4fc3a1b3eaa6c545d workspace-for-rajdeep/ne dist/*.tar.gz
        shell: bash
